### ISSUE TITLE
MacOS: Patch or update Bullet library

### ISSUE THREAD

**Issue by el-dee** [rdb/panda3d-thirdparty#12]
(Follow up issue of https://github.com/panda3d/panda3d/issues/767) Unless compiling with SDK 10.6, bullet compilation fails with the following errors:

<pre>
panda3d-thirdparty/build/bullet-prefix/src/bullet/src/LinearMath/btVector3.h:330:7: error: argument value 10880 is outside the valid range [0, 255] [-Wargument-outside-range]
panda3d-thirdparty/build/bullet-prefix/src/bullet/src/LinearMath/btMatrix3x3.h:882:17: error: argument value 10880 is outside the valid range [0, 255] [-Wargument-outside-range]
</pre>

This has been fixed upstream, https://github.com/bulletphysics/bullet3/pull/2232 but we need to either update the version of bullet downloaded or patch the code before compiling.

**Comment by rdb** [comment]
I think I have already updated the 1.10.4.1 thirdparty download to manually fix this for 1.10, but it would indeed be good to update the Bullet version for master.  Feel free to make a PR here (so that we can check the CI).

**Comment by el-dee** [comment]
Where was the update done ? I will do the same modification so that there is no differences between the 1.10 and master version.

**Comment by rdb** [comment]
I think I did it manually to the 1.10.4.1 .tar.gz file just to get the CI unstuck.  I just applied the fix to the headers mentioned in the linked PR manually.  The (slightly more) sustainable solution is to add a sed rule to the repo here, but then we might as well just update the Bullet version.

**Comment by el-dee** [comment]
Patching the file or adding a sed script is something I can do. Updating the Bullet library is, on the other hand, way out of my league (well, changing the git hash and recompile is easy but I'm not a Bullet user and I can't validate that nothing is broken)

**Comment by rdb** [comment]
> well, changing the git hash and recompile is easy

This is what would be required.  If there are issues with the new Bullet versions then we may well catch it when running the unit tests.

**Comment by el-dee** [comment]
I updated the version to match https://github.com/bulletphysics/bullet3/pull/2232 panda builds without problem and the bullet unit tests are all OK.
I can push as is (after testing with SDK 10.6) or try with the latest version of Bullet, it's as you wish.

**Comment by rdb** [comment]
Since #13 was reverted in 7a09e922dc926d5db0e2d6fbaf240369033069a3, I've just applied 137f76400242bf9ccb2ccb68f9e56c89ddb1ef72.
